### ISSUE TITLE
Firmware status?

### ISSUE THREAD

**Issue by gadyke** [hekkelek/amiga-keyboard#2]
Forgive me, as this isn't quite an "issue" but it's the easiest way I can find to get in touch.

You mention in passing in your README that the firmware for the STM isn't quite perfect but generally works. Can you comment on any of the issues it has? I'm seriously looking at building one of these boards as part of a wider 500+ replica build (so therefore also replacing the mitsumi controller too), but it'd be good to know if it's 99% perfect or more like 50%...

Thanks!

Greg

**Comment by hekkelek** [comment]
Currently, it works, but I'm not entirely sure about the timings. So expect that it's not 100% timing accurate. But so far, I didn't encounter any serious problems. So I would say it's more like 99% perfect.

The only known issue it has is the reset handling (Ctrl+LAmiga+RAmiga). According to the protocol description, Amiga keyboards should send a special message to the motherboard before the reset line being pulled and in certain circumstances, the OS can tell the keyboard to wait a few seconds before pulling the reset line. This is not implemented as per today.

But of course, if you encounter any errors, I'll happily help to debug and fix it, provided you use the same MCU and pinout.

**Comment by gadyke** [comment]
That's really helpful thank you!

This is a different topic so apologies for stretching the use of the issue system further still. Looking at the switch mounts on the board I'm a little confused as to which type of Cherry switch is intended, or whether it's designed to be able to accept any type of switch by including all four possible pin positions for each key.

By default I would normally go for something like [this](https://www.mouser.co.uk/ProductDetail/540-MX1A-11NW), with no diode and no LED. Can you share the precise model you ended up using?

Thanks again,

Greg

**Comment by hekkelek** [comment]
Any type of "Cherry MX compatible" switch should fit. In my prototype I used the PCB-mounted (5-pin) version of Gateron Browns. They fit, but since Gateron is known to use a little bigger fixation pins, a bit of force should be applied when assembling. The one you linked should fit perfectly.

The LEDs are entirely optional even in original Cherry MX switches (except for caps lock). Diodes are placed at the bottom of the PCB, so you don't need switches that have integrated diodes.

**Comment by HeathenUK** [comment]
Hopefully a final question for now - have I read the schematic right, are the resistors on each key switch 0 Ohm?

G

**Comment by hekkelek** [comment]
No, they're marked as optional. If you want LEDs, you'll need to choose a resistor value appropriate for that specific LED. The only exception is the caps lock LED, where I used a 1 kOhm resistor (R9) -- compatible with most red LEDs.

**Comment by hekkelek** [comment]
So "Opc." on the schematic means optional.
