### ISSUE TITLE
Firmware

### ISSUE THREAD

**Issue by Kwiatki75** [hekkelek/amiga-keyboard#3]
Hi . Could you share the firmware for this project ?

**Comment by hekkelek** [comment]
Hi. The firmware is in the fw/ directory.

**Comment by hekkelek** [comment]
Or, you mean the firmware binary?

**Comment by Kwiatki75** [comment]
Yes - i'mean firmware binary.

**Comment by hekkelek** [comment]
Ok, I have commited it to fw/release/ directory.
