### ISSUE TITLE
BOM?

### ISSUE THREAD

**Issue by vejinnovem** [hekkelek/amiga-keyboard#4]
Hello, it seems I can't find any BOM for this project.
A friend of mine ordered a PCB for me and I already have all mx switches soldered in but I can't find, what kind of resistors, diodes or capacitors should I order.

**Comment by hekkelek** [comment]
Hi!
I've added the schematic export and the BOM to the hw/fab/ directory. 
The Power/FDD/HDD LEDs need some experimenting and probably their pins need to be bended before soldering. This is why resistors R104--R115 have no specified values yet, but fitting 1kOhms resistors would work fine.
There are optional resistors (marked by "Opc.") under the key switches if you want backlit keys. The resistor values should be chosen depending on the LED colors you choose.

**Comment by vejinnovem** [comment]
Oh man, thanks so much for the... sudden response!

**Comment by hekkelek** [comment]
You're welcome. If you have any questions, feel free to ask.
