### ISSUE TITLE
ROW0 shorted together?

### ISSUE THREAD

**Issue by vejinnovem** [hekkelek/amiga-keyboard#5]
I finally made it work. Every single key works as intented, except for the ROW0. (ESC, F1-F10, NUM-left-bracket, NUM7, NUM5, NUM1, NUM2).
No matter what key from this row I press, every other keys are pressed together. It doesn't seem to be too much solder anywhere.
The diodes are correct, the resistor on this row is nowhere shorted and every part keeps the same resistance to ground as the other, working parts.
Maybe you may enlighten me, where else can I look?
![image](https://user-images.githubusercontent.com/30325517/211147869-53042a24-209f-485d-8801-eda52cbf42f0.png)

**Comment by hekkelek** [comment]
Sounds like your resistor R98 is not soldered properly, has incorrect value, or is defective. The reason why I think that is that without a pullup resistor the ROW0 line will stay low for a long time (after all, long wires on a PCB have significant capacitance), and so the software will read 0 from ROW0 for all COL0...15 combinations.

Can you send me a photo about your R98?

**Comment by vejinnovem** [comment]
I tried taking a photo of it but it would be not crystal-clear anyway, so I just resoldered the resistor.
Seems like it wasn't connected properly to the row (it's actually my first attempt with any smd soldering, using regular solder-iron instead of hot-air solution.
Now all of the keys work. Thank you, the issue is resolved.
You're the man!

**Comment by hekkelek** [comment]
Great! Have fun using it :)
