### ISSUE TITLE
CPL File

### ISSUE THREAD

**Issue by gotnull** [hekkelek/amiga-keyboard#6]
Is it possible to include a CPL file that includes the correct rotation and placement of each component? This is required by PCBWay to assemble and print.

**Comment by hekkelek** [comment]
I've added the CPL file. Keep in mind that there are differences between PCB manufacturers and sometimes the orientation is different for components depending on if they are packed in reel or tray. So the orientations should be checked and modified if required.

Also, I don't recommend printing the support plate for the keyboard -- it just does not hold up well. Instead, I recommend to CNC mill it from 1.5 mm FR4 epoxy plate.

**Comment by gotnull** [comment]
Thanks so much for doing that. I did come across the following mechanical keyboard option for the A500 here although they don’t offer a CPL file and after reaching out I haven’t yet heard a response.

https://github.com/HenrykRichter/A500KB/tree/main/PCB

Would it at all be possible to generate a CPL for this as well?

**Comment by hekkelek** [comment]
That project is designed using KiCAD. Different software. And although it is possible to export the pick & place files, I won't do it because it's not my project. BTW you can find lots of resources about KiCAD, and as it is a free and open source software, you can do it yourself too.
