### ISSUE TITLE
Issues Programming the Microcontroller  

### ISSUE THREAD

**Issue by HardwareHuligan** [hekkelek/amiga-keyboard#9]
hello I'm having issues  programing  the STM8S003K3T6C  in StM32CubeProgrammer or Stm32 St link utility   same error "no stm32 target found "  . sorry total noob here  any help with how to hex flash would be greatly appreciated   -
Thanks  !

**Comment by hekkelek** [comment]
Hi! Well, the problem is you tried to program an STM8 using an STM32 programmer software. Two totally different microcontrollers. I'd suggest to use ST Visual Programmer (see https://www.st.com/en/development-tools/stvp-stm8.html ) for flashing the hex file.

**Comment by HardwareHuligan** [comment]
Thanks and sorry totally new  to all this  - Love your keyboard  again THANK YOU
